name: CI/CD Pipeline for Docker App

on:
  push:
    branches:
      - main
    tags:
      - 'v*' 
  pull_request:
    branches:
      - main

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

  setup_python:
    runs-on: ubuntu-latest
    needs: checkout_code  
    steps:  
      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt  

  build_and_push:
    runs-on: ubuntu-latest
    needs: setup_python 
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          IMAGE_TAG=v${{ github.run_number }} 
          docker build -t nourinnn/devops-ci-cd:${IMAGE_TAG} .

      - name: Push Image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          IMAGE_TAG=v${{ github.run_number }}  
          docker push nourinnn/devops-ci-cd:${IMAGE_TAG}