name: CI Pipeline for Docker App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nourinnn/devops-ci-cd:v${{ github.run_number }}

  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Devops-CD
        uses: actions/checkout@v3
        with:
          repository: 'Nourin-nnn/Devops-CD'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify the image in the deployment file
        run: |
          git config user.email "nourin114cse.cuet@gmail.com"
          git config user.name "Nourin-nnn"
          sed -i "s+nourinnn/devops-ci-cd.*+nourinnn/devops-ci-cd:v${{ github.run_number }}+g" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Updated image tag to v${{ github.run_number }}"
          git push origin main
