name: CI Pipeline for Docker App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/devops-ci-cd:v${{ github.run_number }}

  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Devops-CD
        uses: actions/checkout@v3
        with:
          repository: 'Nourin-nnn/Devops-CD'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Modify the image in the deployment file
        run: |
          git config user.email "${{secrets.GIT_EMAIL}}"
          git config user.name "${{secrets.GIT_USERNAME}}"

          # Update the image tag using DOCKER_NAME
          sed -i "s|image: ${{ secrets.DOCKER_NAME }}/devops-ci-cd:v.*|image: ${{ secrets.DOCKER_NAME }}/Devops-CI:v${{ github.run_number }}|g" k8s/deployment.yaml

          # Show the changes for verification
          cat k8s/deployment.yaml

          # Commit and push changes
          git add k8s/deployment.yaml
          git commit -m "Update image tag to v${{ github.run_number }}"
          git push origin main
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}